import json
import logging
import uuid

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DeleteView, DetailView, TemplateView, UpdateView

from apps.utils.fineuploader.sign import FineUploaderSignMixIn
from apps.utils.views.basic import LoginRequiredAccessMixin

from .forms import *
from .models import *

logger = logging.getLogger(__name__)


class S3ImageDetailView(LoginRequiredAccessMixin, DetailView):
    model = S3Image
    template_name = 's3images/detail.html'

    def get_context_data(self, **kwargs):
        context = super(S3ImageDetailView, self).get_context_data(**kwargs)
        return context


class S3ImageTitleUpdateView(LoginRequiredAccessMixin, UpdateView):
    model = S3Image
    form_class = S3ImageTitleUpdateForm

    def get_template_names(self):
        return 'form.html'

    def get_success_url(self):
        return reverse('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(S3ImageTitleUpdateView, self).get_context_data(**kwargs)
        context['title'] = _('Update Image Title')
        return context


class S3ImageDeleteView(LoginRequiredAccessMixin, DeleteView):
    model = S3Image
    back_url = None

    def get_queryset(self):
        return S3Image.objects.all()

    def get_success_url(self):
        if self.back_url:
            return self.back_url
        return reverse('home')

    def get_context_data(self, **kwargs):
        context = super(S3ImageDeleteView, self).get_context_data(**kwargs)
        self.back_url = self.request.META.get('HTTP_REFERER')
        context['back_url'] = self.back_url
        return context


class S3ImageUploadView(LoginRequiredAccessMixin, TemplateView):
    template_name = 's3images/image-uploader.html'
    fineuploader_item_limit = 1
    s3_acl = 'public-read'

    def get_fineuploader_storage_dirname(self):
        return settings.S3IMAGE_INCOMING_KEYPATH

    def get_fineuploader_success_endpoint(self):
        return reverse('s3image:upload-success')

    def get_context_data(self, **kwargs):
        context = super(S3ImageUploadView, self).get_context_data(**kwargs)

        context['fineuploader_request_endpoint'] = settings.S3FILE_ENDPOINT.rstrip('/')
        context['fineuploader_accesskey'] = settings.S3IMAGE_PUBLIC_KEY
        context['fineuploader_success_endpoint'] = self.get_fineuploader_success_endpoint()
        context['fineuploader_signature_endpoint'] = reverse('s3image:upload-signee')
        context['fineuploader_max_size'] = settings.S3IMAGE_MAX_SIZE
        context['fineuploader_item_limit'] = self.fineuploader_item_limit
        context['s3_acl'] = self.s3_acl

        # The actual UUID will be generated by fineuploader so ignore now
        context['fineuploader_storage_dirname'] = self.get_fineuploader_storage_dirname()

        return context


# Create your views here.
class S3ImageUploadSuccessEndpointView(View):
    http_method_names = ['post',]

    def post_s3image_save(self, s3image):
        pass

    def get_response_data(self, s3image):
        response_data =  {
            'redirectURL': s3image.get_absolute_url()
        }
        return response_data

    def post(self, request, *args, **kwargs):
        """ This is where the upload will send a POST request after the
        file has been stored in S3.
        """
        # Note that Fine Uploader will still send the bucket, key, filename, UUID, and etag (if available) as well
        #print('success_redirect GET: ' + str(self.request.POST))

        response = HttpResponse()
        if not (self.request.POST.get(u'name') and self.request.POST.get(u'key') and self.request.POST.get(u'uuid')):
            response.status_code = 405
            return response

        name = self.request.POST.get(u'name')
        key = self.request.POST.get(u'key')
        image_uuid = self.request.POST.get(u'uuid')

        # DO SOMETHING
        logger.info('Uploaded image file successfully: name={0}, key={1}, uuid={2}'.format(name,
                                                                                           key,
                                                                                           image_uuid))

        real_uuid = uuid.UUID(image_uuid)
        s3image = S3Image.objects.create_image(uuid=real_uuid, title=name, key=key, request=request)

        self.post_s3image_save(s3image)

        response.status_code = 200
        response['Content-Type'] = "application/json"
        response_data =  self.get_response_data(s3image)
        response.content = json.dumps(response_data)

        return response

    @method_decorator(login_required)
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super(S3ImageUploadSuccessEndpointView, self).dispatch(request, *args, **kwargs)


class S3ImageUploadSignView(FineUploaderSignMixIn, View):
    private_key = settings.S3IMAGE_PRIVATE_KEY
    bucket_name = settings.S3IMAGE_BUCKET_NAME
    max_size = settings.S3IMAGE_MAX_SIZE
