# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3file', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gid', models.PositiveIntegerField(unique=True)),
                ('slug', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('major_version', models.IntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.IntegerField(default=0, verbose_name='Minor')),
                ('patch_version', models.IntegerField(default=0, verbose_name='Patch')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('released', models.BooleanField(default=False, verbose_name='Mark as released (published)')),
                ('released_on', models.DateField(blank=True, null=True, verbose_name='Released Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3file.s3file')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_scripts', to='org.org')),
            ],
            options={
                'ordering': ['org', 'name', 'gid'],
                'unique_together': {('org', 'name', 'major_version', 'minor_version', 'patch_version')},
            },
        ),
    ]
