# Generated by Django 3.2.8 on 2021-11-03 23:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('bucket', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=1600, unique=True)),
                ('ext', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'S3 Image',
                'verbose_name_plural': 'S3 Images',
                'ordering': ['bucket', 'key'],
            },
        ),
    ]
