# Generated by Django 3.2.8 on 2021-11-03 23:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.configattribute.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAttributeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[apps.configattribute.models.validate_config_name])),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Attribute Name',
                'verbose_name_plural': 'Configuration Attribute Names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=64, validators=[apps.configattribute.models.validate_config])),
                ('data', models.JSONField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='update_on')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configattribute.configattributename')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Attribute',
                'verbose_name_plural': 'Configuration Attributes',
                'ordering': ['target', 'name'],
                'unique_together': {('target', 'name')},
            },
        ),
    ]
