# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physicaldevice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=28, unique=True)),
                ('index', models.IntegerField(default=0)),
                ('last_id', models.BigIntegerField(default=0)),
                ('last_reboot_ts', models.DateTimeField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('selector', models.PositiveIntegerField(default=0)),
                ('process_engine_ver', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamers', to='physicaldevice.device')),
            ],
            options={
                'verbose_name': 'Device Streamer',
                'verbose_name_plural': 'Device Streamers',
                'ordering': ['device', 'index'],
                'unique_together': {('device', 'index')},
            },
        ),
        migrations.CreateModel(
            name='StreamerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_first_id', models.BigIntegerField(blank=True, null=True)),
                ('original_last_id', models.BigIntegerField(blank=True, null=True)),
                ('actual_first_id', models.BigIntegerField(blank=True, null=True)),
                ('actual_last_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('device_sent_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('incremental_id', models.BigIntegerField(blank=True, null=True)),
                ('time_epsilon', models.FloatField(blank=True, default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='streamer.streamer')),
            ],
        ),
    ]
