# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPropertyOrgTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean')], default='str', max_length=4)),
                ('name', models.CharField(max_length=48)),
                ('default', models.CharField(blank=True, default='', max_length=256)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_defaults', to='org.org')),
            ],
            options={
                'verbose_name': 'Property Org Template',
                'verbose_name_plural': 'Property Org Templates',
                'ordering': ['org', 'name'],
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GenericPropertyOrgEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_enums', to='org.org')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enums', to='property.genericpropertyorgtemplate')),
            ],
            options={
                'verbose_name': 'Property Org Enum Value',
                'verbose_name_plural': 'Property Org Enum Values',
                'ordering': ['template', 'value'],
                'unique_together': {('template', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GenericProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.SlugField(max_length=42)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean')], default='str', max_length=4)),
                ('name', models.CharField(max_length=40)),
                ('str_value', models.CharField(blank=True, default='', max_length=256)),
                ('is_system', models.BooleanField(blank=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['target', 'name'],
                'unique_together': {('target', 'name')},
            },
        ),
    ]
