# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datablock', '0001_initial'),
        ('vartype', '0001_initial'),
        ('org', '0001_initial'),
        ('project', '0001_initial'),
        ('physicaldevice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorgraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(blank=True, default='', max_length=60, verbose_name='Short Description')),
                ('slug', models.SlugField(max_length=20)),
                ('lid', models.IntegerField(blank=True, default=0, verbose_name='Variable ID')),
                ('units', models.CharField(blank=True, default='', max_length=10)),
                ('multiplication_factor', models.IntegerField(default=1)),
                ('division_factor', models.IntegerField(default=1)),
                ('offset', models.FloatField(default=0.0)),
                ('decimal_places', models.IntegerField(default=0)),
                ('mdo_label', models.CharField(blank=True, default='', max_length=10)),
                ('raw_value_format', models.CharField(blank=True, default='<L', max_length=5)),
                ('app_only', models.BooleanField(blank=True, default=False)),
                ('web_only', models.BooleanField(blank=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_variables', to=settings.AUTH_USER_MODEL)),
                ('derived_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_variables', to='stream.streamvariable')),
                ('input_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='vartype.vartypeinputunit')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='org.org')),
                ('output_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='vartype.vartypeoutputunit')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='project.project')),
                ('var_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='vartype.vartype')),
            ],
            options={
                'verbose_name': 'Stream Variable',
                'verbose_name_plural': 'Stream Variables',
                'ordering': ['slug'],
                'unique_together': {('project', 'lid')},
            },
        ),
        migrations.CreateModel(
            name='StreamId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='', max_length=42)),
                ('var_lid', models.PositiveIntegerField(blank=True, default=0, verbose_name='Variable ID')),
                ('var_name', models.CharField(default='', max_length=30)),
                ('data_type', models.CharField(choices=[('00', '00 - Not Set'), ('D0', 'D0 - Single Value'), ('E0', 'E0 - Unstructured Events'), ('E1', 'E1 - Unstructured Events wth encoded data'), ('E2', 'E2 - Unstructured Events with Data Pointer'), ('E3', 'E3 - Unstructured Events with UTC timestamp')], default='00', max_length=2, verbose_name='Data Type')),
                ('data_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Label')),
                ('multiplication_factor', models.IntegerField(blank=True, null=True)),
                ('division_factor', models.IntegerField(blank=True, null=True)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('mdo_type', models.CharField(choices=[('V', 'Use Variable: F = Ov + V * Mv/Dv'), ('S', 'Use Stream: F = Os + V * Ms/Ds')], default='V', max_length=2, verbose_name='Factor source')),
                ('mdo_label', models.CharField(blank=True, default='', max_length=10)),
                ('raw_value_format', models.CharField(blank=True, default='<L', max_length=5)),
                ('is_encoded', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamids', to='datablock.datablock')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_streamids', to=settings.AUTH_USER_MODEL)),
                ('derived_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_streamids', to='stream.streamid')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamids', to='physicaldevice.device')),
                ('input_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streamids', to='vartype.vartypeinputunit')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamids', to='org.org')),
                ('output_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streamids', to='vartype.vartypeoutputunit', verbose_name='Display units')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streamids', to='project.project')),
                ('var_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streamids', to='vartype.vartype')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streamids', to='stream.streamvariable')),
            ],
            options={
                'verbose_name': 'Stream ID',
                'verbose_name_plural': 'Stream IDs',
                'ordering': ['slug'],
                'unique_together': {('project', 'device', 'variable', 'block')},
            },
        ),
        migrations.CreateModel(
            name='DisplayWidgetInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived_unit_selection', models.CharField(blank=True, default='', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('output_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgetinstances', to='vartype.vartypeoutputunit')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgetinstances', to='stream.streamid')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgetinstances', to='stream.streamvariable')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgetinstances', to='sensorgraph.displaywidgettemplate')),
            ],
            options={
                'verbose_name': 'Display Widget Instance',
                'verbose_name_plural': 'Display Widget Instances',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StreamSystemVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_variables', to='project.project')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_variables', to='stream.streamvariable')),
            ],
            options={
                'verbose_name': 'Stream System Variable',
                'verbose_name_plural': 'Stream System Variables',
                'ordering': ['project', 'variable'],
                'unique_together': {('variable', 'project')},
            },
        ),
    ]
