# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3images', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_sku', models.CharField(max_length=50, verbose_name='SKU/Name')),
                ('internal_sku', models.CharField(blank=True, default='', max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('type', models.CharField(choices=[('BTC', 'Controller'), ('SEN', 'Sensor'), ('COM', 'Communication'), ('IOT', 'Other IOTile')], max_length=3)),
                ('major_version', models.IntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.IntegerField(default=0, verbose_name='Minor')),
                ('patch_version', models.IntegerField(default=0, verbose_name='Patch')),
                ('active', models.BooleanField(default=True)),
                ('hw_tag', models.CharField(blank=True, default='', max_length=20)),
                ('hw_name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_components', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='s3images.S3Image')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='org.org')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ['external_sku', 'major_version', 'minor_version', 'patch_version'],
                'unique_together': {('external_sku', 'major_version', 'minor_version', 'patch_version')},
            },
        ),
    ]
