# Generated by Django 3.2.8 on 2021-11-03 23:44

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3file', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('config', models.JSONField(blank=True, null=True)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=42), blank=True, default=list, size=None)),
                ('generator', models.CharField(choices=[('default', 'General - Default'), ('end_of_trip', 'Shipping - End of Trip'), ('analytics', 'Shipping - Analytics')], default='default', max_length=15, verbose_name='Report template')),
                ('interval', models.CharField(choices=[('x', 'No (Manual only)'), ('d', 'Run daily'), ('w', 'Run weekly (on Sundays)'), ('m', 'Run monthly (end of month)')], default='x', max_length=2)),
                ('notification_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='org.org')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['org', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedUserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('source_ref', models.CharField(default='', max_length=39, null=True)),
                ('status', models.CharField(blank=True, choices=[('GS', 'Scheduled...'), ('G0', 'Generating...'), ('G1', 'Report Generation Completed'), ('GE', 'Generation Failure')], default='G0', max_length=2, verbose_name='Status')),
                ('public', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('index_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3file.s3file')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='org.org')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='report.userreport')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['org', 'created_on', 'label'],
            },
        ),
    ]
