version: '2'

services:

  db1:
    image: postgres:11.8
    command: -c fsync=False
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  db2:
    image: postgres:11.8
    command: -c fsync=False
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - discovery.type=single-node

  builder:
    build:
      image: iotile/builder
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app
    cached: true

  webapp:
    build:
      image: iotile/webapp
      context: ./webapp/
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/var/app/webapp
      - ./server:/var/app/server
      - ./staticfiles:/var/app/staticfiles
    cached: true

  dynamodb:
    image: peopleperhour/dynamodb

  web:
    build:
      image: iotile/web
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/var/staticfiles
    depends_on:
      - dynamodb
      - db1
      - db2
      - es
    encrypted_env_file: codeship.env.test.encrypted
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - DJANGO_SERVER_MODE=Test
      - DJANGO_SECRET_KEY=test-dummy-key1
      - PRODUCTION=False
      - DOCKER=True
      - DEBUG=True
      - SERVER_TYPE=dev
      - DATABASE_DEFAULT_URL=postgres://postgres:postgres@db1/postgres
      - DATABASE_STREAMDATA_URL=postgres://postgres:postgres@db2/postgres
      - SEARCH_URL=es:9200
      - SECRET_KEY=nosecret
      - DOMAIN_NAME=127.0.0.1:8000
      - DOMAIN_BASE_URL=http://127.0.0.1:8000
      - WEBAPP_BASE_URL=http://127.0.0.1:4200
      - STREAMER_REPORT_DROPBOX_PRIVATE_KEY=changeme
      - STREAMER_REPORT_DROPBOX_PUBLIC_KEY=changeme
      - S3IMAGE_PRIVATE_KEY=changeme
      - S3IMAGE_PUBLIC_KEY=changeme
      - GOOGLE_API_KEY=changeme
      - RECAPTCHA_SITE_KEY=changeme
      - RECAPTCHA_SECRET_KEY=changeme
      - DYNAMODB_URL=http://dynamodb@dynamodb:8000/dynamodb
      - TWILIO_FROM_NUMBER=+14432724468
      - TWILIO_ACCOUNT_SID=changeme
      - TWILIO_AUTH_TOKEN=changeme
