version: '3.7'
services:

  db1:
    image: postgres:11.8
    command: -c fsync=False
    environment:
      - POSTGRES_PASSWORD=postgres

  db2:
    image: postgres:11.8
    command: -c fsync=False
    environment:
      - POSTGRES_PASSWORD=postgres

  dynamodb:
    image: peopleperhour/dynamodb

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - cluster.name=iotile_cloud-testing-cluster
      - discovery.type=single-node

  web:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    depends_on:
      - dynamodb
      - db1
      - db2
      - es
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - DJANGO_SERVER_MODE=Test
      - DJANGO_SECRET_KEY=test-dummy-key1
      - PRODUCTION=False
      - DEBUG=True
      - SERVER_TYPE=dev
      - DATABASE_DEFAULT_URL=postgres://postgres:postgres@db1/postgres
      - DATABASE_STREAMDATA_URL=sqlite:///db2.sqlite3
      - SECRET_KEY=nosecret
      - DOMAIN_NAME=127.0.0.1:8000
      - DOMAIN_BASE_URL=http://127.0.0.1:8000
      - STREAMER_REPORT_DROPBOX_PRIVATE_KEY=changeme
      - STREAMER_REPORT_DROPBOX_PUBLIC_KEY=changeme
      - S3IMAGE_PRIVATE_KEY=changeme
      - S3IMAGE_PUBLIC_KEY=changeme
      - GOOGLE_API_KEY=changeme
      - RECAPTCHA_SITE_KEY=changeme
      - RECAPTCHA_SECRET_KEY=changeme
      - DYNAMODB_URL=http://dynamodb@dynamodb:8000/dynamodb
      - SEARCH_URL=es:9200
      - TWILIO_AUTH_TOKEN=changeme
      - TWILIO_ACCOUNT_SID=changeme
      - TWILIO_FROM_NUMBER=changeme
    command: sh runtest.sh
