version: '3.7'
services:

  db1:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=postgres

  db2:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=postgres

  redis1:
    restart: always
    image: redis:2.8

  dynamodb:
    image: peopleperhour/dynamodb

  sqs:
    image: s12v/elasticmq
    restart: always
    ports:
      - "9324:9324"
    volumes:
      - ./sqs_local:/etc/elasticmq

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      # Remove this when moving to several nodes, if ever
      - discovery.type=single-node

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/www/static
    depends_on:
      - web

  web:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    ports:
      - "5000:8000"
    command: /var/app/runserver.sh
    depends_on:
      - db1
      - db2
      - redis1
      - dynamodb
      - sqs
      - es
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - DJANGO_ENV_FILE=.docker.env
      - DJANGO_SECRET_KEY=stage-dummy-key1
      - PRODUCTION=False
      - DOCKER=True
      - DEBUG=True
      - DATABASE_DEFAULT_URL=postgres://postgres:postgres@db1/postgres
      - DATABASE_STREAMDATA_URL=postgres://postgres:postgres@db2/postgres
      - SEARCH_URL=es:9200
      - REDIS_HOSTNAME=redis1
      - REDIS_PORT=6379
      - USE_WORKER=True
      - DYNAMODB_URL=http://dynamodb@dynamodb:8000/dynamodb
      - SQS_URL=http://sqs:9324
      - TWILIO_FROM_NUMBER=+14432724468
      - TWILIO_ACCOUNT_SID=twilio-dummy
      - TWILIO_AUTH_TOKEN=twilio-dummy

  worker:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    command: /usr/bin/supervisord -c /var/app/supervisord.conf
    depends_on:
      - db1
      - db2
      - redis1
      - dynamodb
      - sqs
      - es
    environment:
      - USE_WORKER=True
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - DJANGO_ENV_FILE=.docker.env
      - DJANGO_SECRET_KEY=stage-dummy-key1
      - PRODUCTION=False
      - DOCKER=True
      - DEBUG=True
      - DATABASE_DEFAULT_URL=postgres://postgres:postgres@db1/postgres
      - DATABASE_STREAMDATA_URL=postgres://postgres:postgres@db2/postgres
      - SEARCH_URL=es:9200
      - REDIS_HOSTNAME=redis1
      - REDIS_PORT=6379
      - DYNAMODB_URL=http://dynamodb@dynamodb:8000/dynamodb
      - SQS_URL=http://sqs:9324
      - TWILIO_FROM_NUMBER=+14432724468
      - TWILIO_ACCOUNT_SID=twilio-dummy
      - TWILIO_AUTH_TOKEN=twilio-dummy


