version: '3.7'
services:

  db1:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=postgres

  db2:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=postgres

  redis1:
    restart: always
    image: redis:2.8
    ports:
      - "6379:6379"

  dynamodb:
    image: peopleperhour/dynamodb
    ports:
      - "8001:8000"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      # Remove this when moving to several nodes, if ever
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "9000:80"
    volumes:
      - ./staticfiles:/www/static
    depends_on:
      - web

  web:
    build:
      context: ./server/
    volumes:
      - ./logs:/var/app/logs
      - ./server:/var/app
      - ./staticfiles:/www/static
    expose:
      - "8000"
    ports:
      - "5000:8000"
    command: /var/app/runserver.sh
    depends_on:
      - db1
      - db2
      - redis1
      - dynamodb
      - es
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.docker
      - DJANGO_ENV_FILE=.docker.env
      - DJANGO_SECRET_KEY=stage-dummy-key1
      - PRODUCTION=False
      - DOCKER=True
      - DEBUG=True
      - DATABASE_DEFAULT_URL=postgres://postgres:postgres@db1/postgres
      - DATABASE_STREAMDATA_URL=postgres://postgres:postgres@db2/postgres
      - SEARCH_URL=es:9200
      - REDIS_HOSTNAME=redis1
      - REDIS_PORT=6379
      - USE_WORKER=False
      - DYNAMODB_URL=http://dynamodb@dynamodb:8001/dynamodb
      - TWILIO_FROM_NUMBER=+14432724468
      - TWILIO_ACCOUNT_SID=twilio-dummy
      - TWILIO_AUTH_TOKEN=twilio-dummy
