# Generated by Django 3.2.8 on 2021-11-03 23:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3images', '0001_initial'),
        ('component', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_sku', models.CharField(max_length=50, verbose_name='SKU/Name')),
                ('internal_sku', models.CharField(blank=True, default='', max_length=50)),
                ('family', models.CharField(default='', max_length=50)),
                ('major_version', models.IntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.IntegerField(default=0, verbose_name='Minor')),
                ('patch_version', models.IntegerField(default=0, verbose_name='Patch')),
                ('released_on', models.DateField(verbose_name='Released Date')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('os_tag', models.PositiveIntegerField(default=0, verbose_name='Device OS Tag')),
                ('os_major_version', models.PositiveIntegerField(default=0, verbose_name='Device OS Major Version')),
                ('os_minor_version', models.PositiveIntegerField(default=0, verbose_name='Device OS Major Version')),
                ('hw_tag', models.PositiveIntegerField(default=0, verbose_name='Device HW Tag')),
                ('hw_major_version', models.PositiveIntegerField(default=0, verbose_name='Device HW Major Version')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('components', models.ManyToManyField(blank=True, to='component.Component')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='s3images.S3Image')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='org.org')),
            ],
            options={
                'verbose_name': 'Device Template',
                'verbose_name_plural': 'Device Templates',
                'ordering': ['external_sku', 'major_version', 'minor_version', 'patch_version'],
                'unique_together': {('external_sku', 'major_version', 'minor_version', 'patch_version')},
            },
        ),
        migrations.CreateModel(
            name='DeviceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='component.component')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='devicetemplate.devicetemplate')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('template', 'component', 'number')},
            },
        ),
    ]
