# Generated by Django 3.2.8 on 2021-11-03 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('stream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_streamaliases', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamaliases', to='org.org')),
            ],
            options={
                'verbose_name': 'Stream Alias',
                'verbose_name_plural': 'Stream Aliases',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='StreamAliasTap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='streamalias.streamalias')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_streamaliastaps', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamaliastaps', to='stream.streamid')),
            ],
            options={
                'verbose_name': 'Stream Alias Tap',
                'verbose_name_plural': 'Stream Alias Taps',
                'ordering': ['id'],
            },
        ),
    ]
