# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorgraph', '0001_initial'),
        ('org', '0001_initial'),
        ('physicaldevice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=24)),
                ('block', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='completed_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_blocks', to='physicaldevice.device')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_blocks', to='org.org')),
                ('sg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_blocks', to='sensorgraph.sensorgraph')),
            ],
            options={
                'verbose_name': 'Data block',
                'verbose_name_plural': 'Data blocks',
                'ordering': ['device', 'block'],
                'unique_together': {('device', 'block')},
            },
        ),
    ]
