# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major_version', models.IntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.IntegerField(default=0, verbose_name='Minor')),
                ('patch_version', models.IntegerField(default=0, verbose_name='Patch')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('active', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Org Template',
                'verbose_name_plural': 'Org Templates',
                'ordering': ['name', 'major_version', 'minor_version', 'patch_version'],
                'unique_together': {('name', 'major_version', 'minor_version', 'patch_version')},
            },
        ),
    ]
