# Generated by Django 3.2.8 on 2021-11-03 23:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vartype', '0001_initial'),
        ('stream', '0001_initial'),
        ('project', '0001_initial'),
        ('physicaldevice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filter State',
                'verbose_name_plural': 'Filter States',
                'ordering': ['filter', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_transitions', to='streamfilter.state')),
            ],
            options={
                'verbose_name': 'State Transition',
                'verbose_name_plural': 'State Transitions',
                'ordering': ['src', 'dst'],
            },
        ),
        migrations.CreateModel(
            name='StreamFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_filters', to='physicaldevice.device')),
                ('input_stream', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_filter', to='stream.streamid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_filters', to='project.project')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_filters', to='stream.streamvariable')),
            ],
            options={
                'verbose_name': 'Stream Filter',
                'verbose_name_plural': 'Stream Filters',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='StreamFilterTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('bu', 'Buffer (no-op)'), ('eq', 'Equal (==)'), ('ne', 'Not Equal (!=)'), ('le', 'Less or equal than (<=)'), ('ge', 'Greater or equal than (>=)'), ('lt', 'Less than (<)'), ('gt', 'Greater than (>)')], max_length=2)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('user_threshold', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='streamfilter.streamfilter')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='streamfilter.statetransition')),
                ('user_output_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_unit', to='vartype.vartypeoutputunit')),
            ],
            options={
                'verbose_name': 'Stream Filter Trigger',
                'verbose_name_plural': 'Stream Filter Triggers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StreamFilterAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.CharField(choices=[('entry', 'On Entry'), ('exit', 'On Exit')], default='entry', max_length=5)),
                ('type', models.CharField(choices=[('eml', 'Send Email Notification'), ('sms', 'Send SMS Notification'), ('slk', 'Send Slack Notification'), ('cus', 'Custom Action'), ('drv', 'Derive Stream Action'), ('rpt', 'Report Generation Action'), ('smry', 'Summary Report Generation Action')], max_length=5)),
                ('extra_payload', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='streamfilter.state')),
            ],
            options={
                'verbose_name': 'Stream Filter Action',
                'verbose_name_plural': 'Stream Filter Actions',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='statetransition',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='streamfilter.streamfilter'),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_transitions', to='streamfilter.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='streamfilter.streamfilter'),
        ),
        migrations.AlterUniqueTogether(
            name='statetransition',
            unique_together={('filter', 'src', 'dst')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('filter', 'slug')},
        ),
    ]
