# Generated by Django 3.2.8 on 2021-11-03 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s3file', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('type', models.CharField(choices=[('os', 'OS Image'), ('app', 'App Script')], max_length=5)),
                ('tag', models.PositiveIntegerField(default=0, verbose_name='Tag')),
                ('major_version', models.IntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.IntegerField(default=0, verbose_name='Minor')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('released', models.BooleanField(default=False, verbose_name='Mark as released (published)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3file.s3file')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_files', to='org.org')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('type', 'tag', 'major_version', 'minor_version')},
            },
        ),
    ]
