# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_slug', models.CharField(default='', max_length=39)),
                ('timestamp', models.DateTimeField()),
                ('lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Latitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Location',
                'verbose_name_plural': 'Device Locations',
                'ordering': ['target_slug', 'timestamp'],
            },
        ),
    ]
