# Generated by Django 3.2.8 on 2021-11-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_slug', models.CharField(default='', max_length=39, null=True)),
                ('project_slug', models.CharField(default='', max_length=12, null=True)),
                ('device_slug', models.CharField(default='', max_length=33, null=True)),
                ('variable_slug', models.CharField(default='', max_length=18, null=True)),
                ('device_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('streamer_local_id', models.PositiveIntegerField(default=0)),
                ('dirty_ts', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('unk', 'unknown'), ('cln', 'clean'), ('drt', 'dirty'), ('utc', 'utc timestamp')], default='unk', max_length=3)),
                ('type', models.CharField(choices=[('Num', 'Number'), ('ITR', 'Internal Type Representation'), ('P-0', 'Packet Start Element'), ('P-1', 'Packet End Element'), ('P-E', 'Packet Data Element')], default='Num', max_length=3)),
                ('value', models.FloatField(blank=True, null=True)),
                ('int_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stream Data Entry',
                'verbose_name_plural': 'Stream Data Entries',
                'ordering': ['streamer_local_id', 'stream_slug', 'timestamp'],
            },
        ),
    ]
