# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: s3image

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 256
  timeout: 300
  stage: dev
  region: us-east-1
  deploymentBucket: iotile-cloud-serverless-s3image-${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::iotile-cloud-media"
        - "arn:aws:s3:::iotile-cloud-media/${self:provider.stage}/incoming/*"
        - "arn:aws:s3:::iotile-cloud-media/${self:provider.stage}/images/*"


# you can add packaging information here
package:
  exclude:
    - README.md
    - event.json

functions:
  resize:
    handler: handler.resize

#   you can add any of the following events
    events:
      - s3:
        bucket: iotile-cloud-media
        event: s3:ObjectCreated:*
