# Generated by Django 3.2.8 on 2021-11-03 23:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('devicescript', '0001_initial'),
        ('fleet', '0001_initial'),
        ('physicaldevice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_criteria', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('side_effect', models.JSONField(blank=True, null=True)),
                ('released_on', models.DateTimeField(blank=True, null=True, verbose_name='Released Date')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='fleet.fleet')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_requests', to='org.org')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devicescript.devicescript')),
            ],
            options={
                'ordering': ['completed_on', 'released_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_on', models.DateTimeField(blank=True, null=True, verbose_name='Last attempted')),
                ('attempt_successful', models.BooleanField(default=False)),
                ('device_confirmation', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ota.deploymentrequest')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_actions', to='physicaldevice.device')),
            ],
            options={
                'ordering': ['deployment', 'device', 'created_on'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVersionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('os', 'OS Version'), ('app', 'App Version')], max_length=3)),
                ('major_version', models.PositiveIntegerField(default=0, verbose_name='Major')),
                ('minor_version', models.PositiveIntegerField(default=0, verbose_name='Minor')),
                ('tag', models.PositiveIntegerField()),
                ('streamer_local_id', models.BigIntegerField(blank=True, default=1)),
                ('updated_ts', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='physicaldevice.device')),
            ],
            options={
                'ordering': ['device', 'type', 'major_version', 'minor_version'],
                'unique_together': {('device', 'type', 'tag', 'major_version', 'minor_version', 'streamer_local_id')},
            },
        ),
    ]
