# Generated by Django 3.2.8 on 2021-11-03 23:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('span', models.CharField(choices=[('d', 'Day'), ('w', 'Week'), ('m', 'Month')], max_length=1)),
                ('task_name', models.CharField(max_length=100)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('total_execution_time', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
            ],
            options={
                'verbose_name': 'Worker Statistics',
                'verbose_name_plural': 'Worker Statistics',
                'ordering': ['timestamp', 'task_name'],
            },
        ),
    ]
