# Generated by Django 3.2.8 on 2021-11-03 23:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=26, unique=True)),
                ('storage_units_full', models.CharField(blank=True, default='', max_length=26)),
                ('stream_data_type', models.CharField(choices=[('00', '00 - Not Set'), ('D0', 'D0 - Single Value'), ('E0', 'E0 - Unstructured Events'), ('E1', 'E1 - Unstructured Events wth encoded data'), ('E2', 'E2 - Unstructured Events with Data Pointer'), ('E3', 'E3 - Unstructured Events with UTC timestamp')], default='00', max_length=2, verbose_name='Data Type')),
                ('is_encoded', models.BooleanField(default=False)),
                ('has_schema', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variable Type',
                'verbose_name_plural': 'Variable Types',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='VarTypeSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.JSONField(blank=True, null=True)),
                ('display_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('var_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='vartype.vartype')),
            ],
            options={
                'verbose_name': 'Variable Type Schema',
                'verbose_name_plural': 'Variable Type Schema',
                'ordering': ['var_type', 'created_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VarTypeDecoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_packet_format', models.CharField(default='', max_length=32)),
                ('packet_info', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('var_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decoder', to='vartype.vartype')),
            ],
            options={
                'verbose_name': 'Variable Type Decoder',
                'verbose_name_plural': 'Variable Type Decoders',
                'ordering': ['var_type', 'created_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VarTypeOutputUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=54, unique=True)),
                ('unit_full', models.CharField(max_length=20)),
                ('unit_short', models.CharField(blank=True, default='', max_length=5)),
                ('m', models.IntegerField(default=1)),
                ('d', models.IntegerField(default=1)),
                ('o', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('decimal_places', models.IntegerField(default=0)),
                ('derived_units', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('var_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_units', to='vartype.vartype')),
            ],
            options={
                'verbose_name': 'Output Unit',
                'verbose_name_plural': 'Output Units',
                'ordering': ['slug'],
                'unique_together': {('var_type', 'unit_full')},
            },
        ),
        migrations.CreateModel(
            name='VarTypeInputUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=54, unique=True)),
                ('unit_full', models.CharField(max_length=20)),
                ('unit_short', models.CharField(blank=True, default='', max_length=5)),
                ('m', models.IntegerField(default=1)),
                ('d', models.IntegerField(default=1)),
                ('o', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('var_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_units', to='vartype.vartype')),
            ],
            options={
                'verbose_name': 'Input Unit',
                'verbose_name_plural': 'Input Units',
                'ordering': ['slug'],
                'unique_together': {('var_type', 'unit_full')},
            },
        ),
    ]
